#lang racket

#| ########### |#
#| Main method |#
#| ########### |#

#| Join prefixes and suffixes search |#
(define (meaning word)
  (printf "Possible meanings for a word\n\n")
  (get_roots_meaning word)
  (get_prefixes_meaning word)
  (get_suffixes_meaning word))


#| ##### |#
#| Roots |#
#| ##### |#

#| Define the rules for the prefixes |#
;; Create the dictionary
(define roots (make-hash))

(define (fill_root_dictionary dictionary_name)
  (dict-set! dictionary_name "acro" "Altura, extremo")
  (dict-set! dictionary_name "adeni" "Glándula")
  (dict-set! dictionary_name "adeno" "Glándula")
  (dict-set! dictionary_name "aero" "Aire")
  (dict-set! dictionary_name "air" "Aire")
  (dict-set! dictionary_name "agogia" "Conductor, seductor")
  (dict-set! dictionary_name "agón" "Lucha, disputa, certamen")
  (dict-set! dictionary_name "agora" "Asamblea, plaza pública, mercado, discurso")
  (dict-set! dictionary_name "agro" "Campo como medio natural")
  (dict-set! dictionary_name "algia" "Dolor, tristeza")
  (dict-set! dictionary_name "alge" "Dolor, tristeza")
  (dict-set! dictionary_name "andra" "Varón")
  (dict-set! dictionary_name "andro" "Varón")
  (dict-set! dictionary_name "anemo" "Viento")
  (dict-set! dictionary_name "anim" "Viento")
  (dict-set! dictionary_name "angio" "Vaso")
  (dict-set! dictionary_name "antropo" "Hombre")
  (dict-set! dictionary_name "archi" "El primero (denota preeminencia y autoridad)")
  (dict-set! dictionary_name "arqui" "El primero (denota preeminencia y autoridad)")
  (dict-set! dictionary_name "arque" "El primero (denota preeminencia y autoridad)")
  (dict-set! dictionary_name "arque" "El primero (denota preeminencia y autoridad)")
  (dict-set! dictionary_name "arquia" "El primero (denota preeminencia y autoridad)")
  (dict-set! dictionary_name "aristo" "Los mejores")
  (dict-set! dictionary_name "aster" "Estrella")
  (dict-set! dictionary_name "astro" "Astro")
  (dict-set! dictionary_name "atmos" "Vapor")
  (dict-set! dictionary_name "atra" "El que cura")
  (dict-set! dictionary_name "auto" "Por sí mismo")
  (dict-set! dictionary_name "axio" "Valor, dignidad")
  (dict-set! dictionary_name "base" "Ir, dar paso")
  (dict-set! dictionary_name "bena" "Ir, dar paso")
  (dict-set! dictionary_name "batico" "Ir, dar paso")
  (dict-set! dictionary_name "baro" "Pesadez, peso, carga, mole, gravedad")
  (dict-set! dictionary_name "biblio" "Papiro, libro")
  (dict-set! dictionary_name "bio" "Vida")
  (dict-set! dictionary_name "bulia" "Voluntad")
  (dict-set! dictionary_name "braqui" "Pequeño, corto, breve")
  (dict-set! dictionary_name "braquio" "Brazo, hombro")
  (dict-set! dictionary_name "braquia" "Brazo, hombro")
  (dict-set! dictionary_name "bromato" "De alimento")
  (dict-set! dictionary_name "caco" "Mal, malo")
  (dict-set! dictionary_name "cali" "Bello")
  (dict-set! dictionary_name "cardia" "Corazón")
  (dict-set! dictionary_name "cardio" "Corazón")
  (dict-set! dictionary_name "carpio" "Fruto")
  (dict-set! dictionary_name "cefala" "Cabeza")
  (dict-set! dictionary_name "cefali" "Cabeza")
  (dict-set! dictionary_name "cefalo" "Cabeza")
  (dict-set! dictionary_name "cine" "Movimiento")
  (dict-set! dictionary_name "cini" "Perro")
  (dict-set! dictionary_name "cino" "Perro")
  (dict-set! dictionary_name "cito" "Célula")
  (dict-set! dictionary_name "clepsi" "Robar")
  (dict-set! dictionary_name "clepto" "Robar")
  (dict-set! dictionary_name "clep" "Robar")
  (dict-set! dictionary_name "copro" "Excremento")
  (dict-set! dictionary_name "cosme" "Belleza, ornamento, orden, equilibrio, cielo")
  (dict-set! dictionary_name "cosmo" "Belleza, ornamento, orden, equilibrio, cielo")
  (dict-set! dictionary_name "copa" "Golpear, pegar, romper")
  (dict-set! dictionary_name "cope" "Golpear, pegar, romper")
  (dict-set! dictionary_name "cracia" "Gobierno")
  (dict-set! dictionary_name "crato" "Poder, autoridad, dominio, soberanía")
  (dict-set! dictionary_name "cracio" "Poder, autoridad, dominio, soberanía")
  (dict-set! dictionary_name "cripti" "Escondido")
  (dict-set! dictionary_name "cripto" "Escondido")
  (dict-set! dictionary_name "criso" "Oro")
  (dict-set! dictionary_name "croni" "Tiempo")
  (dict-set! dictionary_name "crono" "Tiempo")
  (dict-set! dictionary_name "dactilo" "Dedos")
  (dict-set! dictionary_name "deca" "Diez")
  (dict-set! dictionary_name "dema" "Comarca, país, habitantes de un pueblo, ciudadanos")
  (dict-set! dictionary_name "demia" "Comarca, país, habitantes de un pueblo, ciudadanos")
  (dict-set! dictionary_name "demo" "Comarca, país, habitantes de un pueblo, ciudadanos")
  (dict-set! dictionary_name "derma" "Piel")
  (dict-set! dictionary_name "dermico" "Piel")
  (dict-set! dictionary_name "dermo" "Piel")
  (dict-set! dictionary_name "doja" "Opinión")
  (dict-set! dictionary_name "doxo" "Opinión")
  (dict-set! dictionary_name "doma" "Casa, edificio")
  (dict-set! dictionary_name "dome" "Casa, edificio")
  (dict-set! dictionary_name "domo" "Casa, edificio")
  (dict-set! dictionary_name "dromo" "Carrera, recorrido, pista")
  (dict-set! dictionary_name "dinami" "Fuerza, poder, capacidad")
  (dict-set! dictionary_name "dinamo" "Fuerza, poder, capacidad")
  (dict-set! dictionary_name "edro" "Cara")
  (dict-set! dictionary_name "endo" "Dentro")
  (dict-set! dictionary_name "entomo" "Insecto")
  (dict-set! dictionary_name "ergia" "Trabajo, empresa")
  (dict-set! dictionary_name "ergo" "Trabajo, empresa")
  (dict-set! dictionary_name "ero" "Amor, deseo")
  (dict-set! dictionary_name "etni" "Pueblo, raza, nación")
  (dict-set! dictionary_name "etno" "Pueblo, raza, nación")
  (dict-set! dictionary_name "estereo" "Sólido, robusto")
  (dict-set! dictionary_name "estero" "Sólido, robusto")
  (dict-set! dictionary_name "estesia" "Sensación, conciencia")
  (dict-set! dictionary_name "esteti" "Sensación, conciencia")
  (dict-set! dictionary_name "estoma" "Boca")
  (dict-set! dictionary_name "etno" "Pueblo, raza, nación")
  (dict-set! dictionary_name "etni" "Pueblo, raza, nación")
  (dict-set! dictionary_name "eto" "Costumbre, hábito")
  (dict-set! dictionary_name "eti" "Costumbre, hábito")
  (dict-set! dictionary_name "fago" "Que come")
  (dict-set! dictionary_name "fante" "Decir")
  (dict-set! dictionary_name "fasia" "Decir")
  (dict-set! dictionary_name "femi" "Decir")
  (dict-set! dictionary_name "feta" "Decir")
  (dict-set! dictionary_name "fama" "Decir")
  (dict-set! dictionary_name "fame" "Decir")
  (dict-set! dictionary_name "feta" "Decir")
  (dict-set! dictionary_name "fante" "Decir")
  (dict-set! dictionary_name "fasia" "Decir")
  (dict-set! dictionary_name "filia" "Amistad, afecto, amor, benevolencia")
  (dict-set! dictionary_name "filo" "Amistad, afecto, amor, benevolencia")
  (dict-set! dictionary_name "fila" "Amistad, afecto, amor, benevolencia")
  (dict-set! dictionary_name "fito" "Planta, vegetal")
  (dict-set! dictionary_name "fisi" "Naturaleza")
  (dict-set! dictionary_name "fobia" "Miedo, terror, huída")
  (dict-set! dictionary_name "fonia" "Sonido, voz")
  (dict-set! dictionary_name "fono" "Sonido, voz")
  (dict-set! dictionary_name "foto" "Luz")
  (dict-set! dictionary_name "gama" "Tomar mario o mujer")
  (dict-set! dictionary_name "game" "Tomar mario o mujer")
  (dict-set! dictionary_name "gamia" "Tomar mario o mujer")
  (dict-set! dictionary_name "geno" "Nacimiento, origen, linaje")
  (dict-set! dictionary_name "genea" "Nacimiento, origen, linaje")
  (dict-set! dictionary_name "genia" "Nacimiento, origen, linaje")
  (dict-set! dictionary_name "geo" "Tierra")
  (dict-set! dictionary_name "geria" "Viejo, anciano")
  (dict-set! dictionary_name "gero" "Viejo, anciano")
  (dict-set! dictionary_name "gine" "Mujer")
  (dict-set! dictionary_name "ginia" "Mujer")
  (dict-set! dictionary_name "gino" "Mujer")
  (dict-set! dictionary_name "glifi" "Esculpir, grabar, cincelar")
  (dict-set! dictionary_name "glifo" "Esculpir, grabar, cincelar")
  (dict-set! dictionary_name "glipto" "Esculpir, grabar, cincelar")
  (dict-set! dictionary_name "glipt" "Esculpir, grabar, cincelar")
  (dict-set! dictionary_name "gnos" "Conocimiento y ciencia")
  (dict-set! dictionary_name "gono" "Ángulo")
  (dict-set! dictionary_name "grafia" "Grabar y escribir")
  (dict-set! dictionary_name "grafo" "Grabar y escribir")
  (dict-set! dictionary_name "grama" "Escrito, letra, carta")
  (dict-set! dictionary_name "hagio" "Santo")
  (dict-set! dictionary_name "hecto" "Cien")
  (dict-set! dictionary_name "helio" "Sol")
  (dict-set! dictionary_name "hema" "Sangre")
  (dict-set! dictionary_name "hemo" "Sangre")
  (dict-set! dictionary_name "emia" "Sangre")
  (dict-set! dictionary_name "hemera" "Día")
  (dict-set! dictionary_name "hemero" "Día")
  (dict-set! dictionary_name "mero" "Día")
  (dict-set! dictionary_name "hemi" "Semi, medio")
  (dict-set! dictionary_name "hepati" "Hígado")
  (dict-set! dictionary_name "hepato" "Hígado")
  (dict-set! dictionary_name "hepta" "Siete")
  (dict-set! dictionary_name "hetero" "El otro, distinto")
  (dict-set! dictionary_name "hexa" "Seis")
  (dict-set! dictionary_name "hidri" "Agua")
  (dict-set! dictionary_name "hidro" "Agua")
  (dict-set! dictionary_name "hiper" "Sobre, por encima de")
  (dict-set! dictionary_name "hipo" "Caballo")
  (dict-set! dictionary_name "higro" "Húmedo")
  (dict-set! dictionary_name "homo" "Igual, semejante")
  (dict-set! dictionary_name "icon" "Imagen, representación")
  (dict-set! dictionary_name "iso" "Igual")
  (dict-set! dictionary_name "icti" "Pez, pescado")
  (dict-set! dictionary_name "itis" "Inflación")
  (dict-set! dictionary_name "kili" "Mil")
  (dict-set! dictionary_name "kilo" "Mil")
  (dict-set! dictionary_name "laringe" "laringe")
  (dict-set! dictionary_name "laringi" "laringe")
  (dict-set! dictionary_name "laringo" "laringe")
  (dict-set! dictionary_name "latra" "Adoración, culto, servicio")
  (dict-set! dictionary_name "latria" "Adoración, culto, servicio")
  (dict-set! dictionary_name "leuce" "Blanco, reluciente")
  (dict-set! dictionary_name "leuco" "Blanco, reluciente")
  (dict-set! dictionary_name "lisis" "Separación, disolución")
  (dict-set! dictionary_name "lito" "Piedra")
  (dict-set! dictionary_name "logo" "Experto")
  (dict-set! dictionary_name "logismo" "Palabra")
  (dict-set! dictionary_name "logia" "Tratado, estudio")
  (dict-set! dictionary_name "macro" "Grande, mucho")
  (dict-set! dictionary_name "mancia" "Adivinación")
  (dict-set! dictionary_name "mania" "Locura, entusiasmo")
  (dict-set! dictionary_name "maquia" "Lucha, combate")
  (dict-set! dictionary_name "mega" "Grande, importante")
  (dict-set! dictionary_name "melo" "Canto, poesía")
  (dict-set! dictionary_name "mela" "Negro")
  (dict-set! dictionary_name "meno" "Mes, luna")
  (dict-set! dictionary_name "menis" "Mes, luna")
  (dict-set! dictionary_name "meso" "En medio, entre")
  (dict-set! dictionary_name "meta" "Después de, junto a")
  (dict-set! dictionary_name "metro" "Medida, instrumento para medir")
  (dict-set! dictionary_name "micro" "Pequeño")
  (dict-set! dictionary_name "miria" "Diez mil, innumerable")
  (dict-set! dictionary_name "mito" "Hilo")
  (dict-set! dictionary_name "mis" "Odiar, aborrecer")
  (dict-set! dictionary_name "mne" "Recuerdo, memoria")
  (dict-set! dictionary_name "mne" "Recuerdo, memoria")
  (dict-set! dictionary_name "mnemo" "Recuerdo, memoria")
  (dict-set! dictionary_name "mono" "Solo, único, singular")
  (dict-set! dictionary_name "morfe" "Forma, figura")
  (dict-set! dictionary_name "morfo" "Forma, figura")
  (dict-set! dictionary_name "necro" "Muerto")
  (dict-set! dictionary_name "nefri" "Riñón")
  (dict-set! dictionary_name "nefro" "Riñón")
  (dict-set! dictionary_name "neo" "Nuevo")
  (dict-set! dictionary_name "neuma" "Viento, aliento, soplo, vida, alma, espíritu")
  (dict-set! dictionary_name "neumo" "Viento, aliento, soplo, vida, alma, espíritu")
  (dict-set! dictionary_name "neura" "Nervio")
  (dict-set! dictionary_name "neuro" "Nervio")
  (dict-set! dictionary_name "ninfo" "Novia recién casada")
  (dict-set! dictionary_name "nomia" "Regla, norma, orden")
  (dict-set! dictionary_name "oct" "ocho")
  (dict-set! dictionary_name "odont" "Diente")
  (dict-set! dictionary_name "oide" "Imagen, representación")
  (dict-set! dictionary_name "oligo" "Poco, pequeño, escaso")
  (dict-set! dictionary_name "eco" "Casa")
  (dict-set! dictionary_name "ecu" "Casa")
  (dict-set! dictionary_name "oftalmia" "Ojo")
  (dict-set! dictionary_name "oftalmo" "Ojo")
  (dict-set! dictionary_name "oma" "Tumor")
  (dict-set! dictionary_name "onoma" "Nombre, palabra")
  (dict-set! dictionary_name "onomia" "Nombre, palabra")
  (dict-set! dictionary_name "onimo" "Nombre, palabra")
  (dict-set! dictionary_name "onto" "El ser")
  (dict-set! dictionary_name "oplo" "Arma")
  (dict-set! dictionary_name "opsia" "Vista, ojos, mirada")
  (dict-set! dictionary_name "opti" "Vista, ojos, mirada")
  (dict-set! dictionary_name "orama" "Vista, espectáculo")
  (dict-set! dictionary_name "ornito" "Pájaro")
  (dict-set! dictionary_name "orto" "Bien, recto")
  (dict-set! dictionary_name "osis" "Enfermedad")
  (dict-set! dictionary_name "osteo" "Hueso")
  (dict-set! dictionary_name "oto" "Oído")
  (dict-set! dictionary_name "oti" "Oído")
  (dict-set! dictionary_name "peda" "Niño")
  (dict-set! dictionary_name "pedo" "Niño")
  (dict-set! dictionary_name "paleo" "Niño")
  (dict-set! dictionary_name "pan" "Todo, entero, completo")
  (dict-set! dictionary_name "para" "Junto a, a lo largo de, contra")
  (dict-set! dictionary_name "parteno" "Virgen, doncella, célibe")
  (dict-set! dictionary_name "pate" "Sentimiento, desgracia, sufrimiento")
  (dict-set! dictionary_name "pato" "Sentimiento, desgracia, sufrimiento")
  (dict-set! dictionary_name "patia" "Sentimiento, desgracia, sufrimiento")
  (dict-set! dictionary_name "pedia" "Instrucción, niñez")
  (dict-set! dictionary_name "penta" "Cinco")
  (dict-set! dictionary_name "piro" "Fuego, ardor, pasión")
  (dict-set! dictionary_name "plasti" "Modelado")
  (dict-set! dictionary_name "plasma" "Modelado")
  (dict-set! dictionary_name "podo" "Pie")
  (dict-set! dictionary_name "poda" "Pie")
  (dict-set! dictionary_name "polemi" "Lucha")
  (dict-set! dictionary_name "poli" "Mucho, numeroso")
  (dict-set! dictionary_name "polis" "Ciudad, patría, estado")
  (dict-set! dictionary_name "porno" "Prostitución, adulterio")
  (dict-set! dictionary_name "potamo" "Río")
  (dict-set! dictionary_name "presbi" "Viejo, anciano")
  (dict-set! dictionary_name "proto" "El primero")
  (dict-set! dictionary_name "psico" "Alma, espíritu, aliento vital")
  (dict-set! dictionary_name "psiqui" "Alma, espíritu, aliento vital")
  (dict-set! dictionary_name "optero" "Pluma, ala, rama")
  (dict-set! dictionary_name "quiro" "Mano")
  (dict-set! dictionary_name "quiru" "Mano")
  (dict-set! dictionary_name "rea" "Correr, manar")
  (dict-set! dictionary_name "rino" "Nariz")
  (dict-set! dictionary_name "rini" "Nariz")
  (dict-set! dictionary_name "sarco" "Carne")
  (dict-set! dictionary_name "saurio" "Lagarto")
  (dict-set! dictionary_name "scopio" "Mirar, observar, examinar, indagar")
  (dict-set! dictionary_name "seleno" "Luna")
  (dict-set! dictionary_name "sema" "Significado")
  (dict-set! dictionary_name "semi" "Significado")
  (dict-set! dictionary_name "sfera" "Esfera, globo")
  (dict-set! dictionary_name "sofia" "Sabiduría, ciencia")
  (dict-set! dictionary_name "sofi" "Habilidad, destreza")
  (dict-set! dictionary_name "soma" "Cuerpo")
  (dict-set! dictionary_name "stasio" "Postura, estabilidad")
  (dict-set! dictionary_name "stati" "Postura, estabilidad")
  (dict-set! dictionary_name "steno" "Estrecho")
  (dict-set! dictionary_name "steni" "Fuerza")
  (dict-set! dictionary_name "strofe" "Dar vueltas")
  (dict-set! dictionary_name "tanato" "Muerte, homicidio")
  (dict-set! dictionary_name "taqui" "Rápido")
  (dict-set! dictionary_name "teca" "Caja, armario")
  (dict-set! dictionary_name "tele" "Lejos, a lo lejos")
  (dict-set! dictionary_name "teleo" "Fin, acabamiento")
  (dict-set! dictionary_name "teo" "Dios")
  (dict-set! dictionary_name "terapia" "Servicio, cura")
  (dict-set! dictionary_name "termo" "Caliente")
  (dict-set! dictionary_name "tesis" "Proposiciónm aserto")
  (dict-set! dictionary_name "tetra" "Cuatro")
  (dict-set! dictionary_name "tipo" "molde")
  (dict-set! dictionary_name "toco" "Parto, nacimiento, descendencia")
  (dict-set! dictionary_name "tomo" "Corte, parto, porción")
  (dict-set! dictionary_name "tono" "tono")
  (dict-set! dictionary_name "topo" "Lugar")
  (dict-set! dictionary_name "toxi" "Veneno")
  (dict-set! dictionary_name "tumba" "Tumba")
  (dict-set! dictionary_name "trofia" "Alimentar")
  (dict-set! dictionary_name "trofo" "Alimentar")
  (dict-set! dictionary_name "topo" "Lugar, territorio")
  (dict-set! dictionary_name "umba" "Tumba")
  (dict-set! dictionary_name "xeno" "Extranjero, ajeno")
  (dict-set! dictionary_name "xilo" "Madera")
  (dict-set! dictionary_name "zoo" "Ser viviente")
  (dict-set! dictionary_name "zoi" "Ser viviente"))

#| Return the meaning for each root |#
(define (get_roots_meaning word)
  ;; Fill again the roots dictionary to avoid problems with missing information
  (fill_root_dictionary roots)
  ;; Remove all the roots that don't fit in the word
  (for/list ([root (get_roots_to_remove word)])
    ;; Remove the root that doesn't fit in the word of the dictionary
    (remove_element_from_dictionary roots root))
  ;; Remove the keys that are contained by other
  (remove_keys_contained_in_other_key roots)
  ;; Show the roots that fits
  (print_dictionary_in_friendly_format roots)
)

#| Get the roots that do not fit for the word gave to search |#
(define (get_roots_to_remove word)
  (filter (lambda (key_from_list) (not(string-contains? word key_from_list))) (dict-keys roots)))


#| ######## |#
#| Prefixes |#
#| ######## |#

#| Define the rules for the prefixes |#
;; Create the dictionary
(define prefixes (make-hash))

(define (fill_prefix_dictionary dictionary_name)
  (dict-set! dictionary_name "a" "Negación (sin)")
  (dict-set! dictionary_name "an" "Negación (sin)")
  (dict-set! dictionary_name "ana" "Arriba (movimiento de abajo a arriba), enteramente, de nuevo, contra")
  (dict-set! dictionary_name "anfi" "A ambos lados, doble")
  (dict-set! dictionary_name "anti" "Opuesto, contrario")
  (dict-set! dictionary_name "apo" "Aparte, fuera, lejos, con")
  (dict-set! dictionary_name "cata" "Sobre, hacia abajo, enteramente")
  (dict-set! dictionary_name "di" "Dos")
  (dict-set! dictionary_name "dia" "A través de")
  (dict-set! dictionary_name "dis" "Mal, negación")
  (dict-set! dictionary_name "ec" "De, desde, fuera de")
  (dict-set! dictionary_name "ex" "De, desde, fuera de")
  (dict-set! dictionary_name "endo" "Dentro, en el interior")
  (dict-set! dictionary_name "epi" "Encima, sobre")
  (dict-set! dictionary_name "eu" "Bien")
  (dict-set! dictionary_name "hiper" "Sobre, por encima de")
  (dict-set! dictionary_name "hipo" "Debajo de, al pie de")
  (dict-set! dictionary_name "meta" "Después de, junto a")
  (dict-set! dictionary_name "palin" "De nuevo")
  (dict-set! dictionary_name "para" "Junto a, de parte de, contra")
  (dict-set! dictionary_name "peri" "Alrededor, acerca de")
  (dict-set! dictionary_name "pro" "Delante, antes")
  (dict-set! dictionary_name "pros" "al lado, cerca de, hacia")
  (dict-set! dictionary_name "sin" "Con, juntamente, a la vez"))

#| Return the meaning for each prefix |#
(define (get_prefixes_meaning word)
  ;; Fill again the prefixes dictionary to avoid problems with missing information
  (fill_prefix_dictionary prefixes)
  ;; Remove all the prefixes that don't fit in the word
  (for/list ([prefix (get_prefixes_to_remove word)])
    ;; Remove the prefix that doesn't fit in the word of the dictionary
    (remove_element_from_dictionary prefixes prefix))
  ;; Remove the keys that are contained by other
  (remove_keys_contained_in_other_key prefixes)
  ;; Guarantee that is not repeated some key from root
  (remove_keys_contained_in_other_key_different_dictionary roots prefixes)
  ;; Show the prefixes that fits
  (print_dictionary_in_friendly_format prefixes)
)

#| Get the prefixes that do not fit for the word gave to search |#
(define (get_prefixes_to_remove word)
  (filter (lambda (key_from_list) (not(string-prefix? word key_from_list))) (dict-keys prefixes)))


#| ######## |#
#| Suffixes |#
#| ######## |#

#| Define the rules for the suffixes |#
;; Create the dictionary
(define suffixes (make-hash))

(define (fill_suffixes_dictionary dictionary_name)
  (dict-set! dictionary_name "ada" "Semejanza, relación")
  (dict-set! dictionary_name "ia" "Acción, cualidad")
  (dict-set! dictionary_name "ica" "Técnicas o ciencias")
  (dict-set! dictionary_name "tica" "Técnicas o ciencias")
  (dict-set! dictionary_name "ico" "Relativo a")
  (dict-set! dictionary_name "ismo" "Actividad, doctrina, sistema")
  (dict-set! dictionary_name "ista" "Partidario de, oficio, profesión")
  (dict-set! dictionary_name "ita" "Materia dotada de la cualidad de la raíz")
  (dict-set! dictionary_name "itis" "Inflamación, irritación")
  (dict-set! dictionary_name "izar" "Poner en práctica, convertir en")
  (dict-set! dictionary_name "meno" "Participio medio-pasivo")
  (dict-set! dictionary_name "ma" "Resultado de la acción")
  (dict-set! dictionary_name "oma" "Resultado de la acción")
  (dict-set! dictionary_name "osis" "Formación, impulso o conversión (sufijo frecuente en nombre de enfermedades)")
  (dict-set! dictionary_name "sis" "Acción")
  (dict-set! dictionary_name "ta" "Agente")
  (dict-set! dictionary_name "ter" "Agente")
  (dict-set! dictionary_name "terio" "Lugar")
  (dict-set! dictionary_name "to" "Pasivo y posible"))

#| Return the meaning for each prefix |#
(define (get_suffixes_meaning word)
  ;; Fill again the prefixes dictionary to avoid problems with missing information
  (fill_suffixes_dictionary suffixes)
  ;; Remove all the prefixes that don't fit in the word
  (for/list ([suffix (get_suffixes_to_remove word)])
    ;; Remove the prefix that doesn't fit in the word of the dictionary
    (remove_element_from_dictionary suffixes suffix))
  ;; Remove the keys that are contained by other
  (remove_keys_contained_in_other_key suffixes)
  ;; Guarantee that is not repeated some key from root
  (remove_keys_contained_in_other_key_different_dictionary roots suffixes)
  ;; Show the prefixes that fits
  (print_dictionary_in_friendly_format suffixes)
)

#| Get the suffixes that do not fit for the word gave to search |#
(define (get_suffixes_to_remove word)
 (filter (lambda (key_from_list) (not(string-suffix? word key_from_list))) (dict-keys suffixes)))


#| ############## |#
#| Common methods |#
#| ############## |#

#| Remove an element of the dictionary |#
(define (remove_element_from_dictionary dictionary element)
  (dict-remove! dictionary element))

#| Remove keys that are contained in other key in the same dictionary |#
(define (remove_keys_contained_in_other_key dictionary)
  (for/list ([key1 (dict-keys dictionary)])
    (for/list ([key2 (dict-keys dictionary)])
      (cond
        [(and (string-contains? key1 key2) (not(equal? key1 key2))) (remove_element_from_dictionary dictionary key2)]
      )))
  ;; Return the new dictionary
  dictionary)

#| Remove keys that are contained in other key in other dictionary |#
(define (remove_keys_contained_in_other_key_different_dictionary dictionary1 dictionary2)
  (for/list ([key1 (dict-keys dictionary1)])
    (for/list ([key2 (dict-keys dictionary2)])
      (cond
        [(and (string-contains? key1 key2) (not(equal? key1 key2))) (remove_element_from_dictionary dictionary2 key2)]
      )))
  ;; Return the new dictionary
  dictionary2)

#| Print the dictionary in other format |#
(define (print_dictionary_in_friendly_format dictionary)
  (cond
    ;; Print the name of the dictionary
    [(and (equal? dictionary roots) (not(dict-empty? roots))) (printf "Roots\n")]
    [(and (equal? dictionary prefixes) (not(dict-empty? prefixes))) (printf "Prefixes\n")]
    [(and (equal? dictionary suffixes) (not(dict-empty? suffixes))) (printf "Suffixes\n")])
  ;; Print the results in friendly format
  (dict-for-each dictionary (lambda (k v) (printf "~a = ~s\n" k v)))
  (cond
    ;; Avoid blank spaces if they are not necessary
    [(not(dict-empty? dictionary)) (printf "\n")]))